### ISSUE TITLE
ExtentX 1.0 with mongodb issue

### ISSUE THREAD

**Issue by BTGBIMobile** [anshooarora/extentx#104]
I just update the extentx1.0 to match the community edition, but when running got the issue below.
Please help , thanks

com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:375)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:104)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:483)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:80)
	at com.mongodb.Mongo.execute(Mongo.java:818)
	at com.mongodb.Mongo$2.execute(Mongo.java:805)
	at com.mongodb.FindIterableImpl$FindOperationIterable.first(FindIterableImpl.java:207)
	at com.mongodb.FindIterableImpl.first(FindIterableImpl.java:148)
	at com.aventstack.extentreports.reporter.ExtentXReporter.setupProject(ExtentXReporter.java:199)
	at com.aventstack.extentreports.reporter.ExtentXReporter.start(ExtentXReporter.java:165)
	at com.aventstack.extentreports.Report.attach(Report.java:51)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.aventstack.extentreports.ExtentReports.attachReporter(ExtentReports.java:66)

**Comment by BTGBIMobile** [comment]
the port 1337 not used as default for new ExtentXReporter(mongodbhost,1337);? I changed the port to 27017, the issue gone.

**Comment by anshooarora** [comment]
The initialization states the MongoDB port not the server itself..  http://extentreports.com/docs/versions/3/java/#initialize-report
