### ISSUE TITLE
Unable to sails lift due to unexpected token error

### ISSUE THREAD

**Issue by malavparekh** [anshooarora/extentx#111]
connection.js file is as follows
extent: {
  adapter:'sails-mongo',
  host:'localhost' 
  port:27017, 
  database:'extent'
}

I can confirm that the connection details are correct.

I get the following error when I run the following command in the installation directory

C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0>node_modules\.bin\sails lift

info: Starting app...

C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\config\connections.js:3
  **host:'localhost'
      ^
SyntaxError: Unexpected token :**
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\include-all\index.js:129:29
    at Array.forEach (native)
    at requireAll (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\include-all\index.js:44:9)
    at buildDictionary (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails-build-dictionary\index.js:68:14)
    at Function.module.exports.aggregate (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails-build-dictionary\index.js:190:9)
    at Array.loadOtherConfigFiles (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\lib\hooks\moduleloader\index.js:239:27)
    at C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\node_modules\async\lib\async.js:591:38
    at _arrayEach (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\node_modules\async\lib\async.js:85:13)
    at Object.async.auto (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\node_modules\async\lib\async.js:552:9)
    at Hook.loadUserConfig (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\lib\hooks\moduleloader\index.js:237:13)
    at Hook.wrapper [as loadUserConfig] (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\node_modules\lodash\index.js:3095:19)
    at Hook.loadModules (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\lib\hooks\userconfig\index.js:41:18)
    at Hook.wrapper [as loadModules] (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\node_modules\lodash\index.js:3095:19)
    at Array.modules (C:\Users\UserName\Downloads\extentx-community-1.0.0\extentx-community-1.0.0\node_modules\sails\lib\hooks\index.js:79:27)

**Comment by anshooarora** [comment]
You are missing a command after 'localhost'.
