### ISSUE TITLE
Integrate ExtentX with MongoDB running on mlab

### ISSUE THREAD

**Issue by srikanth-vejendla** [anshooarora/extentx#113]
Can you share how to use  mongodb running on mlab??

In connections.js file, what info do we need to provide?

extent: {
  adapter: 'sails-mongo',
  host: 'localhost', // change to host where MongoDB is running
  port: 27017, // change toport where MongoDB is running
  database: 'extent'
}

Example this is my mongodb uri-

mongodb://testuser:testpassword@ds161059.mlab.com:61059/extent

I modified the connections.js file, like this-

extent: {
  adapter: 'sails-mongo',
  host: 'ds161059.mlab.com', // change to host where MongoDB is running
  port: 61059, // change toport where MongoDB is running
  database: 'extent'
}

Note: I created mongo database as 'extent' on mlab

Error:

`error: A hook (`orm`) failed to load!
error: Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: not authorized on extent to execute command { listCollections: true, filter: { name: "author" }, cursor: {} }
    at Function.MongoError.create (/Users/s0v0023/extentx/node_modules/sails-mongo/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/Users/s0v0023/extentx/node_modules/sails-mongo/node_modules/mongodb-core/lib/cursor.js:281:36)
    at Callbacks.emit (/Users/s0v0023/extentx/node_modules/sails-mongo/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at Connection.messageHandler (/Users/s0v0023/extentx/node_modules/sails-mongo/node_modules/mongodb-core/lib/topologies/server.js:249:23)
    at Socket.<anonymous> (/Users/s0v0023/extentx/node_modules/sails-mongo/node_modules/mongodb-core/lib/connection/connection.js:265:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)`

Thanks for your help

**Comment by srikanth-vejendla** [comment]
where do we need configure the user and password that was created on mlab in extentx??
