### ISSUE TITLE
ExtentX crashing

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentx#127]
**Build:** 
766d8c4 

**Stack trace:**
TypeError: Cannot read property 'project' of undefined
    at c:\jit\Extentx\extentx-community-1.0.1\api\controllers\ReportController.js:171:42
    at tryCatcher (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promis
    at Promise._settlePromise (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:548:18
    at Promise._settlePromise0 (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:593:1
    at Promise._settlePromises (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:676:1
    at Promise._fulfill (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:617:18)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\nodeback.js:42:21
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at returnResults (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:154:30)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:86:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\operations.js:78:46
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\adapter\dql.js:164:37
TypeError: Cannot read property 'project' of undefined
    at c:\jit\Extentx\extentx-community-1.0.1\api\controllers\ReportController.js:171:42
    at tryCatcher (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promis
    at Promise._settlePromise (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:548:18
    at Promise._settlePromise0 (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:593:1
    at Promise._settlePromises (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:676:1
    at Promise._fulfill (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:617:18)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\nodeback.js:42:21
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at returnResults (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:154:30)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:86:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\operations.js:78:46
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\adapter\dql.js:164:37
c:\jit\Extentx\extentx-community-1.0.1\node_modules\bson\lib\bson\parser\serializer.js:179
    throw Error("value " + value.source + " must not contain null bytes");
    ^

Error: value ^Xì5

c:\jit\Extentx\extentx-community-1.0.1>

**Comment by gsaimadhu** [comment]
Anshoo, any update on this issue?

**Comment by gsaimadhu** [comment]
**Frequently crashing**
(node:2536) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
c:\jit\Extentx\extentx-community-1.0.1\node_modules\bson\lib\bson\parser\serializer.js:179
    throw Error("value " + value.source + " must not contain null bytes");
    ^

Error: value ^Xï?a?D`☺?;"

c:\jit\Extentx\extentx-community-1.0.1>

**Comment by gsaimadhu** [comment]
I have commented this line and its working fine, not seen any crashes:
//throw Error("value " + value.source + " must not contain null bytes");

**Comment by anshooarora** [comment]
How can I reproduce this?  Are you trying to delete a report when this happens?

**Comment by anshooarora** [comment]
Can you check with the latest build?  Able to see it still?

**Comment by gsaimadhu** [comment]
Anshoo, I checked in the latest build. No crash.
Deleting reports working fine.

**Comment by anshooarora** [comment]
Thanks. Working on a few additional fixes, other issues should also get resolved soon.
