### ISSUE TITLE
ExtentX Breaking execution and not updated report in server Dashboard

### ISSUE THREAD

**Issue by Arunagnz** [anshooarora/extentx#13]
Hi Anshoo,

I have successfully done extent reports implementation in my framework. Now i want to prepare a trents using ExtentX.

I have followed the steps that are mentioned in the site.

1) Started MongoDB in localhost port:27017
2) Sails lift done
3) After started the sails, Noticed changes in MongoDB console regarding open connection.
4) Configured script also.

**Code Snippet:**

extent = new ExtentReports(filePath, true);
		extent.startReporter(ReporterType.DB, (new File(filePath)).getParent() + File.separator + "extent.db");
		extent.x();

**Screenshots:**

![Uploading mongo.PNG…]()

![Uploading sails.PNG…]()

**Actual Result:**

In my test, I'm running test in parallel using TestNG. Either one of the test is failing at every instance. While checking the server report for single test update. their is nothing in the page: http://localhost:1337/

Expecting sample ExtentX project or Tutorial video from your side.

Pl Help me out. Thanks in advance.

**Comment by anshooarora** [comment]
Each time you call `flush()` in your test, report information will be updated in the db.  If you are running your tests from a different machine, do specify the host/port information in `extent.x(host, port)`.  Let me know how it goes.

**Comment by Arunagnz** [comment]
Eventhough everything up and running. Report is not getting update in dashboard. Im running in my local system only that i mentioned earlier. See the below screenshots for reference.

![dashboard](https://cloud.githubusercontent.com/assets/16700286/14954214/328bd630-108e-11e6-9b6d-1a744f003068.PNG)
![mongo](https://cloud.githubusercontent.com/assets/16700286/14954219/3d74c35e-108e-11e6-90c3-fd61429f7f82.PNG)
![sails](https://cloud.githubusercontent.com/assets/16700286/14954222/481948d4-108e-11e6-9e25-94461cfbf97f.PNG)

**Comment by Arunagnz** [comment]
I am using your testNG examples only: https://github.com/anshooarora/extentreports/tree/master/java/extentreports/src/test/java/com/relevantcodes/extentreports

**Comment by anshooarora** [comment]
Were you able to resolve this?  For the testng examples you are running, can you enable ExtentX?  

http://extentreports.relevantcodes.com/extentx/#configure-extentreports

**Comment by Arunagnz** [comment]
I have updated my sample code: 

```
public class SingleLogTest{
	
	public static ExtentReports extent;
	ExtentTest test;

	final String filePath = "src\\reports\\parallelclassX.html";
	
	public synchronized static ExtentReports getReporter(String filePath) {
        if (extent == null) {
        	extent = new ExtentReports(filePath);
        	**extent.startReporter(ReporterType.DB, (new File(filePath)).getParent() + File.separator + "extent.db");
        	extent.x();**
        	
        	extent
                .addSystemInfo("Host Name", "Arun")
                .addSystemInfo("Environment", "Regression");
        }
        
        return extent;
    }
    
    public synchronized static ExtentReports getReporter() {
    	return extent;
    }
	
	@Test
	public void passTest() {
		test = extent.startTest("passTest");
		test.log(LogStatus.PASS, "Pass");
		String video = test.addScreencast("file:///C:\\Downloads\\Video\\small.mp4");
		test.log(LogStatus.INFO,"Enjoy the video", video);
		Reporter.log("User is Logged in and Application is closed | ");
		Assert.assertEquals(test.getRunStatus(), LogStatus.PASS);
	}

	@Test
	public void intentionalFailure() throws Exception {
		test = extent.startTest("intentionalFailure");
		Reporter.log("User is Logged out and Application is closed | ");
		throw new Exception("intentional failure");
	}
	
	@AfterMethod
	protected void afterMethod(ITestResult result) {
		if (result.getStatus() == ITestResult.FAILURE) {
			test.log(LogStatus.FAIL, result.getThrowable());
		} else if (result.getStatus() == ITestResult.SKIP) {
			test.log(LogStatus.SKIP, "Test skipped " + result.getThrowable());
		} else {
			test.log(LogStatus.PASS, "Test passed");
		}
		

		extent.endTest(test);
		extent.flush();
	}

	@BeforeSuite
	public void beforeSuite() {
		extent = getReporter(filePath);
	}

	@AfterSuite
	protected void afterSuite() {
		for (String s : Reporter.getOutput()) { 
		    extent.setTestRunnerOutput(s); 
		}
		extent.close();
	}
}

```
If i commented the two bold lines above, I can able to successfully run the test but if i used ExtentX, I am getting error like below:

Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.NoSuchMethodError: ch.qos.logback.classic.util.ContextInitializer.<init>(Lch/qos/logback/classic/LoggerContext;)V
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:56)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.mongodb.diagnostics.logging.Loggers.shouldUseSLF4J(Loggers.java:63)
	at com.mongodb.diagnostics.logging.Loggers.<clinit>(Loggers.java:32)
	at com.mongodb.connection.BaseCluster.<clinit>(BaseCluster.java:53)
	at com.mongodb.connection.DefaultClusterFactory.create(DefaultClusterFactory.java:55)
	at com.mongodb.Mongo.createCluster(Mongo.java:658)
	at com.mongodb.Mongo.createCluster(Mongo.java:644)
	at com.mongodb.Mongo.<init>(Mongo.java:275)
	at com.mongodb.Mongo.<init>(Mongo.java:271)
	at com.mongodb.MongoClient.<init>(MongoClient.java:171)
	at com.mongodb.MongoClient.<init>(MongoClient.java:148)
	at com.mongodb.MongoClient.<init>(MongoClient.java:138)
	at com.relevantcodes.extentreports.ExtentX.<init>(ExtentX.java:293)
	at com.relevantcodes.extentreports.ExtentReports.x(ExtentReports.java:569)
	at com.extents.usage.SingleLogTest.getReporter(SingleLogTest.java:29)
	at com.extents.usage.SingleLogTest.beforeSuite(SingleLogTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
FAILED CONFIGURATION: @AfterMethod afterMethod([TestResult name=intentionalFailure status=FAILURE method=SingleLogTest.intentionalFailure()[pri:0, instance:com.extents.usage.SingleLogTest@34340fab] output=User is Logged out and Application is closed | ])
java.lang.AbstractMethodError: ch.qos.logback.classic.Logger.trace(Ljava/lang/String;)V
	at com.mongodb.diagnostics.logging.SLF4JLogger.trace(SLF4JLogger.java:41)
	at com.mongodb.connection.DefaultConnectionPool.getPooledConnection(DefaultConnectionPool.java:249)
	at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:90)
	at com.mongodb.connection.DefaultConnectionPool.get(DefaultConnectionPool.java:80)
	at com.mongodb.connection.DefaultServer.getConnection(DefaultServer.java:69)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.getConnection(ClusterBinding.java:86)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:193)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:168)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:394)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:57)
	at com.mongodb.Mongo.execute(Mongo.java:736)
	at com.mongodb.Mongo$2.execute(Mongo.java:723)
	at com.mongodb.FindIterableImpl$FindOperationIterable.first(FindIterableImpl.java:197)
	at com.mongodb.FindIterableImpl.first(FindIterableImpl.java:140)
	at com.relevantcodes.extentreports.ExtentX.getProjectId(ExtentX.java:89)
	at com.relevantcodes.extentreports.ExtentX.insertReport(ExtentX.java:104)
	at com.relevantcodes.extentreports.ExtentX.addTest(ExtentX.java:136)
	at com.relevantcodes.extentreports.Report.finalizeTest(Report.java:370)
	at com.relevantcodes.extentreports.ExtentReports.endTest(ExtentReports.java:832)
	at com.extents.usage.SingleLogTest.afterMethod(SingleLogTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:514)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:215)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:707)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

SKIPPED CONFIGURATION: @AfterMethod afterMethod
FAILED: intentionalFailure
java.lang.Exception: intentional failure
	at com.extents.usage.SingleLogTest.intentionalFailure(SingleLogTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)

SKIPPED: passTest

===============================================
    Default test
    Tests run: 2, Failures: 1, Skips: 1
    Configuration Failures: 1, Skips: 1
===============================================


===============================================
Default suite
Total tests run: 2, Failures: 1, Skips: 1
Configuration Failures: 1, Skips: 2
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@606d8acf: 50 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@73a28541: 18 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 4 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@4aa8f0b4: 5 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@1e81f4dc: 4 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@5c8da962: 4 ms

Provide a solution to solve this issue.

**Comment by veeramanikandanvv** [comment]
@anshooarora ,

I have used server reporting with extentReports 2.41 with the below code, 

eReports=new ExtentReports("HtmlReports.html");
	eReports.x("localhost", xxxx);. 

but when i am using extentReports  3.05,  i am using the below code ,

ExtentHtmlReporter eHtmlReporter=new ExtentHtmlReporter("HtmlReports.html");
	ExtentReports eReports=new ExtentReports();
	ExtentTest test;
ExtentXReporter extentxReporter;
	
	eReports.attachReporter(eHtmlReporter);
	
	
	extentxReporter = new ExtentXReporter("localhost", xxxx);
	extentxReporter.config().setProjectName("veera1");

but i am not getting any data for it in the reports.. please correct me if anything is missed?

**Comment by RaghuveerA** [comment]
Looks like in my case also set project name is not working.
it is throwing null pointer exception.
