### ISSUE TITLE
ExtentX crashing at api\models\Test.js:125

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentx#130]
**Build:**
 766d8c4 

**Stack trace:**
(node:3840) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
user: root
user: root
c:\jit\Extentx\extentx-community-1.0.1\api\models\Test.js:125
        if (test.logs.length === 0)
                ^

TypeError: Cannot read property 'logs' of undefined
    at child.deepPopulateLogElements (c:\jit\Extentx\extentx-community-1.0.1\api\models\Test.js:125:17)
    at child.wrapper [as deepPopulateLogElements] (c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-hook-orm\node_modules\lodash\index.js:3095:19)
    at c:\jit\Extentx\extentx-community-1.0.1\api\controllers\TestController.js:35:18
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at returnResults (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:179:9)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:91:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\operations.js:78:46
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at Cursor.attachRecords (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline-cursor\cursor\cursor.js:78:12)
    at afterPopulateBuffers (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline-cursor\cursor\cursor.js:55:10)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:52:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:550:17
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:544:17
    at _arrayEach (c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:85:13)

c:\jit\Extentx\extentx-community-1.0.1>

**Comment by gsaimadhu** [comment]
**Today it crashed again. The stack trace for troubleshooting:**
info: Server lifted in `c:\jit\Extentx\extentx-community-1.0.1`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: -------------------------------------------------------
debug: :: Mon Apr 17 2017 10:37:46 GMT+0530 (India Standard Time)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
(node:3364) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Test.getTestById -> [Error (E_UNKNOWN) Encountered an unexpected error] Details:  MongoError: server localhost:27017 sockets closed

Test.getTestById -> [Error (E_UNKNOWN) Encountered an unexpected error] Details:  MongoError: server localhost:27017 sockets closed

Test.getTestById -> [Error (E_UNKNOWN) Encountered an unexpected error] Details:  MongoError: server localhost:27017 sockets closed

Test.getTestById -> [Error (E_UNKNOWN) Encountered an unexpected error] Details:  MongoError: server localhost:27017 sockets closed

c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'logs' of undefined
    at child.deepPopulateLogElements (c:\jit\Extentx\extentx-community-1.0.1\api\models\Test.js:125:17)
    at child.wrapper [as deepPopulateLogElements] (c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-hook-orm\node_modules\lodash\index.js:3095:19)
    at c:\jit\Extentx\extentx-community-1.0.1\api\controllers\TestController.js:35:18
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:335:16)
    at error (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:42:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:56:28)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:79:23
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\operations.js:72:21
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:335:16)
    at error (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:42:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:56:28)
    at afterPopulateBuffers (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline-cursor\cursor\cursor.js:54:20)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:52:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:570:21
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:167:37
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline-cursor\cursor\populateBuffers.js:32:24
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\lib\collection.js:101:20
    at handleCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\node_modules\mongodb\lib\utils.js:96:12)

c:\jit\Extentx\extentx-community-1.0.1>

**Comment by anshooarora** [comment]
Can you check the the latest build?

https://github.com/anshooarora/extentx/tree/50892c47dee7d0d68def1678b30cd4d946a151a9

**Comment by gsaimadhu** [comment]
Updated my setup with the latest build. Will let you know if any issues.
