### ISSUE TITLE
ExtentX crashing at Category.js

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentx#133]
**Build:**
 766d8c4 

**Stack trace:**
Error (E_UNKNOWN) :: Encountered an unexpected error
MongoError: server localhost:27017 sockets closed
    at Pool.<anonymous> (c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\node_modules\mongodb-core\lib\topologies\server.js:330:47)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Pool.emit (events.js:194:7)
    at Connection.<anonymous> (c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\node_modules\mongodb-core\lib\connection\pool.js:105:12)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at Socket.<anonymous> (c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\node_modules\mongodb-core\lib\connection\connection.js:145:12)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:509:12)

Details:  MongoError: server localhost:27017 sockets closed

c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'length' of undefined
    at c:\jit\Extentx\extentx-community-1.0.1\api\models\Category.js:87:48
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:335:16)
    at error (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:42:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:56:28)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:264:23
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\operations.js:72:21
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:335:16)
    at error (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:42:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:56:28)
    at afterPopulateBuffers (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline-cursor\cursor\cursor.js:54:20)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:52:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:570:21
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:167:37
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:52:16
    at done (c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:241:17)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\async\lib\async.js:44:16
    at _afterFetchingJunctorRecords (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline-cursor\cursor\populateBuffers.js:120:29)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\sails-mongo\lib\collection.js:101:20

c:\jit\Extentx\extentx-community-1.0.1>

**Comment by anshooarora** [comment]
I am not quite sure how you are getting these errors.  Is your schema corrupted, or has bad data?  Some of these errors are very unusual.
