### ISSUE TITLE
Error at console, while deleting reports

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentx#136]
**Build**
50892c47dee7d0d68def1678b30cd4d946a151a9

**Stack trace:**
TypeError: Cannot read property 'project' of undefined
    at c:\jit\Extentx\extentx-community-1.0.1\api\controllers\ReportController.js:171:23
    at tryCatcher (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:617:18)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\nodeback.js:42:21
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at returnResults (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:154:30)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:86:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\operations.js:78:46
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\adapter\dql.js:164:37
TypeError: Cannot read property 'project' of undefined
    at c:\jit\Extentx\extentx-community-1.0.1\api\controllers\ReportController.js:171:23
    at tryCatcher (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:491:31)
    at Promise._settlePromise (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\promise.js:617:18)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\bluebird\js\release\nodeback.js:42:21
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\factory.js:58:28)
    at returnResults (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:154:30)
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\basic.js:86:16
    at c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\query\finders\operations.js:78:46
    at wrapper (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\lodash\index.js:3592:19)
    at applyInOriginalCtx (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\lib\waterline\utils\normalize.js:324:18)
    at success (c:\jit\Extentx\extentx-community-1.0.1\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)

**Comment by anshooarora** [comment]
Fixed, but its strange that the project is coming as undefined in your case.  It should never be so..  Are you setting your project to something?
