### ISSUE TITLE
Is it possible to specify a different data location for MongoDB while connecting via ExtentX?

### ISSUE THREAD

**Issue by rheab54** [anshooarora/extentx#140]
Hi Anshu
First of all my apologies if this is not the correct forum to post questions. Is it possible to override the dbpath location for MongoDB via ExtentX? Currently it creates a Extentx Db in the default data location.. Is it possible to have something like Extentx1 and ExtentX2? I tried looking at the javadocs and I do not see anything like it. Also the reason i need this is because we have one MongoDB , but we have multiple build pipelines with various projects .. We need to have a report per build + the projects under that build. Current results group  all the builds together on the project name basis only. So i see the last 5 runs based on the projects and not in the build pipeline they were. Hope this makes sense. :)
Thanks in advance

**Comment by anshooarora** [comment]
Why not create separate projects for each using the ExtentAPI?

```
x.config().setProjectName(projectName);
```

**Comment by RaghuveerA** [comment]
Sorry Sir if I have added this here,

above mentioned command is giving null pointer exception.

java.lang.NullPointerException
at com.qa.pfr.ExtentTestNGIReporterListener.generateReport(ExtentTestNGIReporterListener.java:97)
at org.testng.TestNG.generateReports(TestNG.java:1076)
at org.testng.TestNG.run(TestNG.java:1035)
at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
