### ISSUE TITLE
sails lift not working, however mongodb is running

### ISSUE THREAD

**Issue by amitaks2** [anshooarora/extentx#167]
I am unable to connect to mongodb DB server , while i run sails lift command i get below error error:

```
D:\EXTENT\extentx>sails lift
info: Starting app...
error: A hook (`orm`) failed to load!
error: Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?
 Error details:
{ Error: connect ETIMEDOUT 54.80.159.104:61001
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  name: 'MongoError',
  message: 'connect ETIMEDOUT 54.80.159.104:61001' }
    at _createError (D:\EXTENT\extentx\node_modules\sails-mongo\lib\adapter.js:116:23)
    at D:\EXTENT\extentx\node_modules\sails-mongo\lib\adapter.js:119:13
    at D:\EXTENT\extentx\node_modules\sails-mongo\lib\connection.js:25:20
    at D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb\lib\mongo_client.js:276:20
    at D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb\lib\db.js:224:14
    at Server.<anonymous> (D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb\lib\server.js:234:9)
    at Server.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at Pool.<anonymous> (D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb-core\lib\topologies\server.js:269:68)
    at Pool.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (D:\EXTENT\extentx\node_modules\sails-mongo\node_modules\mongodb-core\lib\connection\pool.js:81:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
```
**My connection.js->**

```
module.exports.connections = {
extent: {
    adapter: 'sails-mongo',
    host: 'localhost', // host where MongoDB is running
    port: 27017, // port where MongoDB is running
 //user: 'admin',
    //password: 'admin',
    database: 'extent'
  },
    mlabMongo:{
  
 adapter:'sails-mongo',
 url: 'mongodb://admin:admin@ds161001.mlab.com:61001/extent',
 schema: 'true',
 
  
  }
};
```
**My model.js-- >**

```
module.exports.models = {
connection: 'mlabMongo',
migrate: 'alter',
  hookTimeout: 60000
};
```

**My Package.json-->**

```
{
  "name": "extentx",
  "private": true,
  "version": "1.0.2",
  "description": "AventStack ExtentX Community Version - Report Server for ExtentReports",
  "keywords": [],
  "dependencies": {
    "bcryptjs": "2.3.0",
    "ejs": "2.3.4",
    "grunt": "1.0.1",
    "grunt-contrib-clean": "1.0.0",
    "grunt-contrib-coffee": "1.0.0",
    "grunt-contrib-concat": "1.0.1",
    "grunt-contrib-copy": "1.0.0",
    "grunt-contrib-cssmin": "1.0.1",
    "grunt-contrib-jst": "1.0.0",
    "grunt-contrib-less": "1.3.0",
    "grunt-contrib-uglify": "1.0.1",
    "grunt-contrib-watch": "1.0.0",
    "grunt-sails-linker": "0.10.1",
    "grunt-sync": "0.5.2",
    "include-all": "0.1.6",
    "lodash": "4.15.0",
    "mongodb": "2.1.19",
    "mv": "2.1.1",
    "node-inspector": "^1.1.1",
    "rc": "1.0.1",
    "sails": "0.12.3",
    "sails-disk": "0.10.9",
    "sails-memory": "^0.10.7",
    "sails-mongo": "0.12.0",
    "waterline": "^0.11.11"
  },
  "scripts": {
    "debug": "node debug app.js",
    "start": "node app.js"
  },
  "main": "app.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/amitaks2/extentx.git"
  },
  "author": "AventStack"
}
```
**My mlab Database - >**

mlab_database
![mlab_database](https://cloud.githubusercontent.com/assets/2518755/26722371/4e61f2e8-47ad-11e7-84ef-abd0b1d5932f.png)

Local DB ->
showdb
![showdb](https://cloud.githubusercontent.com/assets/2518755/26722376/54f5452e-47ad-11e7-913a-a193271ba471.png)

Heroku logs -->

```
2017-06-02T09:47:28.895413+00:00 app[web.1]:     at Connection.g (events.js:292:16)
2017-06-02T09:47:28.895413+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-06-02T09:47:28.895414+00:00 app[web.1]:   originalError: 
2017-06-02T09:47:28.895414+00:00 app[web.1]:    { Error: connect ECONNREFUSED 127.0.0.1:27017
2017-06-02T09:47:28.895414+00:00 app[web.1]:        at Object.exports._errnoException (util.js:1018:11)
2017-06-02T09:47:28.895415+00:00 app[web.1]:        at exports._exceptionWithHostPort (util.js:1041:20)
2017-06-02T09:47:28.895415+00:00 app[web.1]:        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
2017-06-02T09:47:28.895415+00:00 app[web.1]:      name: 'MongoError',
2017-06-02T09:47:28.895416+00:00 app[web.1]:      message: 'connect ECONNREFUSED 127.0.0.1:27017' } }
2017-06-02T09:47:47.836781+00:00 heroku[web.1]: Process exited with status 0
2017-06-02T09:47:47.851360+00:00 heroku[web.1]: State changed from starting to crashed
```
please help me to get application deploy ?

**Comment by lgw8186** [comment]
problem solved?  i have the same problem
