### ISSUE TITLE
Can't start extentX server

### ISSUE THREAD

**Issue by Alan1810** [anshooarora/extentx#18]
Hi Anshoo,

I'm trying to install extentX server on ubuntu. I've followed the installation instruction in http://extentreports.relevantcodes.com/extentx/. 
When I run the server (sails lift), I have this error :

_info: Starting app...

/usr/local/extentx/api/models/Test.js:149
    getGroupsWithCounts(matcher, groupBy, sortBy, limit, cb) {
                       ^
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/extentx/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/usr/local/extentx/node_modules/include-all/index.js:44:9)
    at buildDictionary (/usr/local/extentx/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/usr/local/extentx/node_modules/sails-build-dictionary/index.js:160:9)
    at Hook.loadModels (/usr/local/extentx/node_modules/sails/lib/hooks/moduleloader/index.js:279:23)
    at Hook.bound [as loadModels] (/usr/local/extentx/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Array.async.auto.models [as 0] (/usr/local/extentx/node_modules/sails/lib/hooks/orm/load-user-modules.js:23:23)
    at /usr/local/extentx/node_modules/sails/node_modules/async/lib/async.js:484:38
    at _each (/usr/local/extentx/node_modules/sails/node_modules/async/lib/async.js:46:13)_

Can you help me ?

Regards

**Comment by anshooarora** [comment]
Please re-download the extentx package from the homepage.  This was a known issue impacting some *nix distros.  I have uploaded the fix and it should work now.

**Comment by Alan1810** [comment]
It works now with the new package.
Thanks
Regards
