### ISSUE TITLE
MongoException while using ExtentXReporter on local mongodb instance

### ISSUE THREAD

**Issue by srikanthvejendla** [anshooarora/extentx#53]
When i try to use ExtentXReporter on my local instance of extentx &  mongodb, i am encountering below issue-

Error Stack Trace- 

```
INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27019], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
[cluster-ClusterId{value='57c25115fddb066b7b036978', description='null'}-localhost:27019] INFO org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27019
com.mongodb.MongoException: java.lang.NoSuchMethodError: org.bson.codecs.configuration.ChildCodecRegistry.<init>(Lorg/bson/codecs/configuration/ProvidersCodecRegistry;Ljava/lang/Class;)V
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:126)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bson.codecs.configuration.ChildCodecRegistry.<init>(Lorg/bson/codecs/configuration/ProvidersCodecRegistry;Ljava/lang/Class;)V
	at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:37)
	at com.mongodb.connection.RequestMessage.getCodec(RequestMessage.java:245)
	at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:205)
	at com.mongodb.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:75)
	at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
	at com.mongodb.connection.RequestMessage.encode(RequestMessage.java:147)
	at com.mongodb.connection.CommandHelper.sendMessage(CommandHelper.java:88)
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:83)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:43)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:116)
	... 2 more


java.lang.ClassCastException: org.bson.Document cannot be cast to org.bson.conversions.Bson
	at com.mongodb.FindIterableImpl.<init>(FindIterableImpl.java:57)
	at com.mongodb.MongoCollectionImpl.find(MongoCollectionImpl.java:216)
	at com.mongodb.MongoCollectionImpl.find(MongoCollectionImpl.java:211)
	at com.relevantcodes.extentreports.reporter.ExtentXReporter.setupProject(ExtentXReporter.java:193)
	at com.relevantcodes.extentreports.reporter.ExtentXReporter.start(ExtentXReporter.java:161)
	at com.relevantcodes.extentreports.Report.attach(Report.java:38)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.relevantcodes.extentreports.ExtentReports.attachReporter(ExtentReports.java:11)
	at com.samsclub.qa.android.tests.SampleTest.firstTest(SampleTest.java:40)
```

Mongo DB Instance Running Locally on port 27017
extentx App running(using 'sails lift') on http://localhost:1337

My Test Code(Java)-
    

    ExtentReports extentReports;
    ExtentTest test;
    ExtentXReporter extentXReporter;

    @Test
    public void firstTest(){
        extentXReporter=new ExtentXReporter("localhost");
        extentXReporter.config().setProjectName("Sams QA");
        extentXReporter.config().setReportName("Mobile Test Automation");
        extentXReporter.config().setServerUrl("http://localhost:1337/");
        extentReports=new ExtentReports();
        extentReports.attachReporter(extentXReporter);
        try {
            extentReports.createTest("My First Test").addScreenCaptureFromPath("./sample.png").fail("Failed");
        } catch (IOException e) {
            e.printStackTrace();
        }
        extentReports.flush();
    }

My pom.xml with the dependencies, I have added "extentreports-java-3.0.0-SNAPSHOT" to my class path of my project

```

<dependencies>
      <dependency>
          <groupId>org.testng</groupId>
          <artifactId>testng</artifactId>
          <version>6.8</version>
      </dependency>
      <dependency>
          <groupId>io.appium</groupId>
          <artifactId>java-client</artifactId>
          <version>4.1.2</version>
      </dependency>
      <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-api</artifactId>
          <version>1.7.21</version>
      </dependency>
      <dependency>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-simple</artifactId>
          <version>1.7.21</version>
      </dependency>
      <dependency>
          <groupId>org.jsoup</groupId>
          <artifactId>jsoup</artifactId>
          <version>1.9.2</version>
          <scope>test</scope>
      </dependency>
      <dependency>
          <groupId>org.freemarker</groupId>
          <artifactId>freemarker</artifactId>
          <version>2.3.23</version>
      </dependency>
      <dependency>
          <groupId>org.mongodb</groupId>
          <artifactId>bson</artifactId>
          <version>3.0.0-beta2</version>
      </dependency>
      <dependency>
          <groupId>org.mongodb</groupId>
          <artifactId>mongodb-driver</artifactId>
          <version>3.3.0</version>
      </dependency>
      <dependency>
          <groupId>org.mongodb</groupId>
          <artifactId>mongo-java-driver</artifactId>
          <version>3.3.0</version>
      </dependency>
  </dependencies>
```

**Comment by srikanthvejendla** [comment]
@anshooarora Any idea whats going wrong?

**Comment by srikanthvejendla** [comment]
It was dependency issue, works fine

Thanks
