### ISSUE TITLE
Receiving the error "SEVERE: Unable to parse x-csrf-token", and screenshot is not added to the ExtentX Report

### ISSUE THREAD

**Issue by SrikanthKhaja** [anshooarora/extentx#76]
ExtentXReporter configuration gist link
https://gist.github.com/SrikanthKhaja/6b2c5266ad7a52087c0030f0fafbb21b

Simple Test Script for taking screenshot and attaching it to the ExtentHTMLReporter and ExtentXReporter
https://gist.github.com/SrikanthKhaja/cf9838dbe4e4186a1f431ea4890cca0a

When running the above test the screenshot is not attached to the ExtentXReporter (though it is perfectly attaching to the ExtentHTMLReporter) and getting the below error. 

```
Oct 01, 2016 7:52:14 AM com.relevantcodes.extentreports.mediastorage.HttpMediaManager storeCsrfCookie
SEVERE: Unable to parse x-csrf-token
javax.script.ScriptException: TypeError: Cannot call undefined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:439)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:401)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:152)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.relevantcodes.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:76)
	at com.relevantcodes.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:46)
	at com.relevantcodes.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:422)
	at com.relevantcodes.extentreports.Report.lambda$5(Report.java:76)
	at com.relevantcodes.extentreports.Report$$Lambda$27/1338770454.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.relevantcodes.extentreports.Report.addScreenCapture(Report.java:74)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:224)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:230)
	at com.qaninja.ExtentScreenshotTest.testExtentHtmlReportScreenshot(ExtentScreenshotTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
Caused by: <eval>:1 TypeError: Cannot call undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:94)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:149)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:233)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:636)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:437)
	... 39 more

Oct 01, 2016 7:52:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.FileNotFoundException) caught when processing request to {}->http://localhost:1337: sample3.0/abc.png (No such file or directory)
Oct 01, 2016 7:52:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:1337
Oct 01, 2016 7:52:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.FileNotFoundException) caught when processing request to {}->http://localhost:1337: sample3.0/abc.png (No such file or directory)
Oct 01, 2016 7:52:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:1337
Oct 01, 2016 7:52:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.FileNotFoundException) caught when processing request to {}->http://localhost:1337: sample3.0/abc.png (No such file or directory)
Oct 01, 2016 7:52:14 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://localhost:1337
java.io.UncheckedIOException: java.io.FileNotFoundException: sample3.0/abc.png (No such file or directory)
	at com.relevantcodes.extentreports.Report.lambda$5(Report.java:78)
	at com.relevantcodes.extentreports.Report$$Lambda$27/1338770454.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.relevantcodes.extentreports.Report.addScreenCapture(Report.java:74)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:224)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:230)
	at com.qaninja.ExtentScreenshotTest.testExtentHtmlReportScreenshot(ExtentScreenshotTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
Caused by: java.io.FileNotFoundException: sample3.0/abc.png (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.apache.http.entity.mime.content.FileBody.writeTo(FileBody.java:100)
	at org.apache.http.entity.mime.HttpMultipart.doWriteTo(HttpMultipart.java:206)
	at org.apache.http.entity.mime.HttpMultipart.writeTo(HttpMultipart.java:224)
	at org.apache.http.entity.mime.MultipartEntity.writeTo(MultipartEntity.java:183)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.relevantcodes.extentreports.mediastorage.HttpMediaManager.storeMedia(HttpMediaManager.java:108)
	at com.relevantcodes.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:425)
	at com.relevantcodes.extentreports.Report.lambda$5(Report.java:76)
	... 31 more
```

Note: Tried all version of 0.2-alpha, 0.2.1-alpha and also master, but facing the same issue.

**Comment by SrikanthKhaja** [comment]
@anshooarora

**Comment by SrikanthKhaja** [comment]
@anshooarora Can you please look into this.

**Comment by SrikanthKhaja** [comment]
@anshooarora 

Also, i could see the below error on the "Sails lift" Terminal Window. 

`Unable to parse HTTP body- error occurred :: 'Error: Request aborted\n    at IncomingMessage.onReqAborted (/Users/Khaja/Desktop/ExtentX/extentx/node_modules/skipper/node_modules/multiparty/index.js:175:17)\n    at emitNone (events.js:67:13)\n    at IncomingMessage.emit (events.js:166:7)\n    at abortIncoming (_http_server.js:280:11)\n    at Socket.serverSocketCloseListener (_http_server.js:293:5)\n    at emitOne (events.js:82:20)\n    at Socket.emit (events.js:169:7)\n    at TCP._onclose (net.js:477:12)'`

**Comment by anshooarora** [comment]
Get rid of:

```
extentHtmlReporter.config().setAutoCreateRelativePathMedia(true);
```

Make sure the server is running and the URL is set correctly.  If the server goes down, then also you can receive csrf errors.  Let me know how it goes.

**Comment by SrikanthKhaja** [comment]
commented out 

`extentHtmlReporter.config().setAutoCreateRelativePathMedia(true);`

Still getting the below error. The server is running and the URL is also set to localhost. 

```
Oct 01, 2016 8:32:54 AM com.relevantcodes.extentreports.mediastorage.HttpMediaManager storeCsrfCookie
SEVERE: Unable to parse x-csrf-token
javax.script.ScriptException: TypeError: Cannot call undefined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:439)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:401)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:152)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.relevantcodes.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:76)
	at com.relevantcodes.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:46)
	at com.relevantcodes.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:422)
	at com.relevantcodes.extentreports.Report.lambda$5(Report.java:76)
	at com.relevantcodes.extentreports.Report$$Lambda$27/1338770454.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.relevantcodes.extentreports.Report.addScreenCapture(Report.java:74)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:224)
	at com.relevantcodes.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:230)
	at com.qaninja.ExtentScreenshotTest.testExtentHtmlReportScreenshot(ExtentScreenshotTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)
Caused by: <eval>:1 TypeError: Cannot call undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:94)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:149)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:233)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:636)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:437)
	... 39 more

Oct 01, 2016 8:32:54 AM com.relevantcodes.extentreports.mediastorage.HttpMediaManager storeMedia
WARNING: Unable to upload file to server test-output/abc.png
```

**Comment by anshooarora** [comment]
What version of ExtentX is this? MongoDb running on local host? Which OS?

**Comment by SrikanthKhaja** [comment]
@anshooarora I am using ExtentX 0.2.1-alpha. Yes MongoDB is running local and its on Mac OS X version 10.11.6

**Comment by anshooarora** [comment]
Please update your version to ExtentX 0.2.2-alpha and the latest ExtentReports 3.0-pre from either nexus or download from the website.

I have had a few users report similar issues - all Mac OS X.  Is there a local security policy that prohibits this event?  I don't have a mac so unable to check, but I have tested this on Ubuntu, Win7, Win10 - no issues there.  Do you have a different OS that you can test with?

**Comment by SrikanthKhaja** [comment]
I have my friend who is running Mac OS X, the same script ran successfully on his machine. I assume it might be some permissions, but then i had reimaged my Mac OS X last week. I will give a try with the 0.2.2 alpha and 3.0-pre and update you.

**Comment by anshooarora** [comment]
Thanks.  Please let me know how it goes,  especially if its a permissions issue.  I haven't been able to repro this on any of my test boxes so would love to know the reason.

**Comment by SrikanthKhaja** [comment]
@anshooarora I tried with ExtentX 0.2.2-alpha and ExtentReports 3.0 Snapshot, but still getting the same error. 

```
<dependency>
          <groupId>com.relevantcodes</groupId>
          <artifactId>extentreports</artifactId>
          <version>3.0.0-SNAPSHOT</version>
</dependency>
```

I believe, it could be some permissions issue, where mongois unable to serve the screenshots to the report. :(

**Comment by SrikanthKhaja** [comment]
Let me know if you can connect to my system through TeamViewer, if so please do send me an email on moinuddinbtech14@gmail.com and i will share the TeamViewer details and I can give access to my Mac OS system.

**Comment by SrikanthKhaja** [comment]
@anshooarora I do not see the ExtentX 0.2.2-alpha, branch. Are you referring to the correct branch?

**Comment by SrikanthKhaja** [comment]
@anshooarora If you do not have Mac OS X, you can give it a try with MacinCloud, a cloud solution for Mac OS X. I have changed/ updated the user permissions on /data/db and also tried to uninstall completely and reinstall the mongodb. None of that worked yet.

**Comment by anshooarora** [comment]
A Windows7 user has reported this issue as well on 1 system internal to their lab.  Can you debug once and check if the csrf token is returned?  If its an issue with the json parser, its going to be a simpler fix than figuring out why the server isn't reached even if its local.

**Comment by pthewizard** [comment]
Having the same problem on centos. What is the reason behind it?

**Comment by prasanta-biswas** [comment]
this basically happening due to local admin account... from root account it is working fine.
