### ISSUE TITLE
Getting mongodb error while running test

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentx#84]
I have configured extentx in a different server and running my test from local machine. Both are in the same network. I get exception when I run my tests.

**extentxReporter= new ExtentXReporter("10.10.4.37",27017);**//MongoDB, Nodejs and extentx is                                                                                                                     //installed in 10.10.4.37
**extentxReporter.config().setServerUrl("http://10.10.4.37:1337/");**

**Exception:**

Oct 19, 2016 6:34:41 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Cluster created with settings {hosts=[10.10.4.37:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
Oct 19, 2016 6:34:41 PM com.mongodb.diagnostics.logging.JULLogger log
INFO: Exception in monitor thread while connecting to server 10.10.4.37:27017
com.mongodb.MongoSocketException: 10.10.4.37: unknown error
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:188)
	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
	at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: platform10: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at com.mongodb.ServerAddress.getSocketAddress(ServerAddress.java:186)
	... 5 more

**Comment by pthewizard** [comment]
I found the solution.
