### ISSUE TITLE
Getting error while uploading the screenshot to ExtentX

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#91]
Getting the following error while I'm running the test in a CentOS VM from admin user:

```
Dec 07, 2016 12:21:30 PM com.aventstack.extentreports.mediastorage.HttpMediaManager storeCsrfCookie
SEVERE: Unable to parse x-csrf-token
javax.script.ScriptException: TypeError: Cannot call undefined in <eval> at line number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:439)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:401)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:397)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:152)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:79)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:48)
	at com.aventstack.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:425)
	at com.aventstack.extentreports.Report.lambda$addScreenCapture$5(Report.java:79)
	at com.aventstack.extentreports.Report$$Lambda$34/1366581056.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.aventstack.extentreports.Report.addScreenCapture(Report.java:77)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:644)
	at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:650)
	at com.seamless.ers.TestClass.AgentPortal.AgentPortalTests.tearDownMethod(AgentPortalTests.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
Caused by: <eval>:1 TypeError: Cannot call undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128)
	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:100)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:102)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:94)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:149)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:233)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:636)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:437)
	... 39 more

Dec 07, 2016 12:21:30 PM com.aventstack.extentreports.mediastorage.HttpMediaManager storeMedia
WARNING: Unable to upload file to server /home/admin/standard-automation/TestReport/Screenshots/verifyCreditTransfer/verifyCreditTransfer-Run-1.png
```

Note: This is not happening when I'm running the tests using root user.

**Comment by anshooarora** [comment]
I would recommend upgrading to extentreports-3.0.2 and ExtentX 1.0.0, a lot of bug fixes available.  This was a long open bug from extentreports side also which was resolved with the recent upgrades.

**Comment by prasanta-biswas** [comment]
Already using the latest versions. Still getting this issue

**Comment by harsh976** [comment]
I am also getting same thing @prasanta-biswas  you got any fix ?
